/* Variáveis auxiliares */
DECLARE total_respondentes_brasil INT64;

SET (total_respondentes_brasil) = (
	SELECT AS STRUCT COUNT(*)
	FROM `sprint1-mvp.state_of_data.respostas` 
	WHERE MORA_NO_BRASIL = true
); 







/* Visão dos tipo de linguagem utilizadas pelos respondentes */
WITH LINGUAGENS AS (
		SELECT 	
			COUNTIF(USA_SQL = TRUE) as SQL, 
			COUNTIF(USA_R = TRUE) as R, 
			COUNTIF(USA_PYTHON = TRUE) as PYTHON, 
			COUNTIF(USA_C_CPP_CSHARP = TRUE) as C_CPP_CSHARP, 
			COUNTIF(USA_DOT_NET = TRUE) as DOT_NET, 
			COUNTIF(USA_JAVA = TRUE) as JAVA, 
			COUNTIF(USA_JULIA = TRUE) as JULIA, 
			COUNTIF(USA_SAS_STATA = TRUE) as SAS_STATA, 
			COUNTIF(USA_VISUAL_BASIC_VBA = TRUE) as VISUAL_BASIC_VBA, 
			COUNTIF(USA_SCALA = TRUE) as SCALA, 
			COUNTIF(USA_MATLAB = TRUE) as MATLAB, 
			COUNTIF(USA_PHP = TRUE) as PHP, 
			COUNTIF(USA_JAVASCRIPT = TRUE) as JAVASCRIPT
		FROM    `sprint1-mvp.state_of_data.respostas` 
		WHERE   MORA_NO_BRASIL = true
)

SELECT 	LINGUAGEM,
				RESPONDENTES,
				ROUND((RESPONDENTES/total_respondentes_brasil)*100, 2) as Percentual 
FROM LINGUAGENS
UNPIVOT(RESPONDENTES 
	FOR LINGUAGEM IN 
	(	SQL,		R,
		PYTHON,		C_CPP_CSHARP,
		DOT_NET,		JAVA,
		JULIA,		SAS_STATA,
		VISUAL_BASIC_VBA,		SCALA,
		MATLAB,		PHP,		JAVASCRIPT))
ORDER BY RESPONDENTES DESC;







/* Visão das plataformas de nuvem utilizadas pelos respondentes */
WITH PLATAFORMAS AS (
		SELECT 	
			COUNTIF(USA_AZURE = TRUE) as AZURE, 
			COUNTIF(USA_AWS = TRUE) as AWS, 
			COUNTIF(USA_GOOGLE_CLOUD = TRUE) as GOOGLE_CLOUD
		FROM    `sprint1-mvp.state_of_data.respostas` 
		WHERE   MORA_NO_BRASIL = true
)

SELECT 	PLATAFORMA,
		RESPONDENTES,
		ROUND((RESPONDENTES/total_respondentes_brasil)*100, 2) as Percentual 
FROM PLATAFORMAS
UNPIVOT(RESPONDENTES 
	FOR PLATAFORMA IN 
	(	AZURE, AWS, GOOGLE_CLOUD))
ORDER BY RESPONDENTES DESC;





/* Visão dos bancos de dados utilizados pelos respondentes */
WITH SGBDS AS (
		SELECT 	
		COUNTIF(USA_MYSQL = TRUE) as MYSQL, 
		COUNTIF(USA_ORACLE = TRUE) as ORACLE, 
		COUNTIF(USA_SQL_SERVER = TRUE) as SQL_SERVER, 
		COUNTIF(USA_AMAZON_AURORA_RDS = TRUE) as AMAZON_AURORA_RDS, 
		COUNTIF(USA_DYNAMODB = TRUE) as DYNAMODB, 
		COUNTIF(USA_COACHDB = TRUE) as COACHDB, 
		COUNTIF(USA_CASSANDRA = TRUE) as CASSANDRA, 
		COUNTIF(USA_MONGODB = TRUE) as MONGODB, 
		COUNTIF(USA_MARIADB = TRUE) as MARIADB, 
		COUNTIF(USA_DATOMIC = TRUE) as DATOMIC, 
		COUNTIF(USA_S3 = TRUE) as S3, 
		COUNTIF(USA_POSTGRESQL = TRUE) as POSTGRESQL, 
		COUNTIF(USA_ELASTICSEARCH = TRUE) as ELASTICSEARCH, 
		COUNTIF(USA_DB2 = TRUE) as DB2, 
		COUNTIF(USA_MICROSOFT_ACCESS = TRUE) as MICROSOFT_ACCESS, 
		COUNTIF(USA_SQLITE = TRUE) as SQLITE, 
		COUNTIF(USA_SYBASE = TRUE) as SYBASE, 
		COUNTIF(USA_FIREBASE = TRUE) as FIREBASE, 
		COUNTIF(USA_VERTICA = TRUE) as VERTICA, 
		COUNTIF(USA_REDIS = TRUE) as REDIS, 
		COUNTIF(USA_NEO4J = TRUE) as NEO4J, 
		COUNTIF(USA_GOOGLE_BIGQUERY = TRUE) as GOOGLE_BIGQUERY, 
		COUNTIF(USA_GOOGLE_FIRESTORE = TRUE) as GOOGLE_FIRESTORE, 
		COUNTIF(USA_AMAZON_REDSHIFT = TRUE) as AMAZON_REDSHIFT, 
		COUNTIF(USA_AMAZON_ATHENA = TRUE) as AMAZON_ATHENA, 
		COUNTIF(USA_SNOWFLAKE = TRUE) as SNOWFLAKE, 
		COUNTIF(USA_DATABRICKS = TRUE) as DATABRICKS, 
		COUNTIF(USA_HBASE = TRUE) as HBASE, 
		COUNTIF(USA_PRESTO = TRUE) as PRESTO, 
		COUNTIF(USA_SPLUNK = TRUE) as SPLUNK, 
		COUNTIF(USA_SAP_HANA = TRUE) as SAP_HANA, 
		COUNTIF(USA_HIVE = TRUE) as HIVE, 
		COUNTIF(USA_FIREBIRD = TRUE) as FIREBIRD
		FROM    `sprint1-mvp.state_of_data.respostas` 
		WHERE   MORA_NO_BRASIL = true
)

SELECT 	SGBD,
		RESPONDENTES,
		ROUND((RESPONDENTES/total_respondentes_brasil)*100, 2) as Percentual 
FROM SGBDS
UNPIVOT(RESPONDENTES 
	FOR SGBD IN 
	(	MYSQL,ORACLE,SQL_SERVER,
		AMAZON_AURORA_RDS,DYNAMODB,COACHDB,
		CASSANDRA,MONGODB,MARIADB,DATOMIC,
		S3,POSTGRESQL,ELASTICSEARCH,DB2,
		MICROSOFT_ACCESS,SQLITE,SYBASE,
		FIREBASE,VERTICA,REDIS,
		NEO4J,GOOGLE_BIGQUERY,GOOGLE_FIRESTORE,
		AMAZON_REDSHIFT,AMAZON_ATHENA,
		SNOWFLAKE,DATABRICKS,HBASE,
		PRESTO,SPLUNK,SAP_HANA,
		HIVE,FIREBIRD))
ORDER BY RESPONDENTES DESC;





/* Visão das ferramentas de visualização de dados utilizadas pelos respondentes */
WITH FERRAMENTAS AS (
		SELECT 	
		COUNTIF(USA_POWERBI = TRUE) as POWERBI, 
		COUNTIF(USA_QLIK_VIEW_SENSE = TRUE) as QLIK_VIEW_SENSE, 
		COUNTIF(USA_TABLEAU = TRUE) as TABLEAU, 
		COUNTIF(USA_METABASE = TRUE) as METABASE, 
		COUNTIF(USA_SUPERSET = TRUE) as SUPERSET, 
		COUNTIF(USA_REDASH = TRUE) as REDASH, 
		COUNTIF(USA_MICROSTRATEGY = TRUE) as MICROSTRATEGY, 
		COUNTIF(USA_IBM_ANALYTICS_COGNOS = TRUE) as IBM_ANALYTICS_COGNOS, 
		COUNTIF(USA_SAP_BO = TRUE) as SAP_BO, 
		COUNTIF(USA_ORACLE_BUSINESS = TRUE) as ORACLE_BUSINESS, 
		COUNTIF(USA_AMAZON_QUICKSIGHT = TRUE) as AMAZON_QUICKSIGHT, 
		COUNTIF(USA_SALESFORCE_EINSTEIN = TRUE) as SALESFORCE_EINSTEIN, 
		COUNTIF(USA_MODE = TRUE) as MODE, 
		COUNTIF(USA_ALTERYX = TRUE) as ALTERYX, 
		COUNTIF(USA_BIRST = TRUE) as BIRST, 
		COUNTIF(USA_LOOKER = TRUE) as LOOKER, 
		COUNTIF(USA_GOOGLE_DATA_STUDIO = TRUE) as GOOGLE_DATA_STUDIO, 
		COUNTIF(USA_SAS_VISUAL_ANALYTICS = TRUE) as SAS_VISUAL_ANALYTICS, 
		COUNTIF(USA_GRAFANA = TRUE) as GRAFANA, 
		COUNTIF(USA_SPOTFIRE = TRUE) as SPOTFIRE, 
		COUNTIF(USA_PENTAHO = TRUE) as PENTAHO,
		COUNTIF(USA_EXCEL_PLANILHA_GOOGLE = TRUE) as EXCEL_PLANILHA_GOOGLE, 
		COUNTIF(NAO_USA_FERRAMENTA_VISUALIZACAO = TRUE) as NAO_USA_FERRAMENTA
		FROM    `sprint1-mvp.state_of_data.respostas` 
		WHERE   MORA_NO_BRASIL = true
)

SELECT 	FERRAMENTA,
		RESPONDENTES,
		ROUND((RESPONDENTES/total_respondentes_brasil)*100, 2) as Percentual 
FROM FERRAMENTAS
UNPIVOT(RESPONDENTES 
	FOR FERRAMENTA IN 
	(	POWERBI,QLIK_VIEW_SENSE,
		TABLEAU,METABASE,
		SUPERSET,REDASH,
		MICROSTRATEGY,IBM_ANALYTICS_COGNOS,
		SAP_BO,ORACLE_BUSINESS,
		AMAZON_QUICKSIGHT,SALESFORCE_EINSTEIN,
		MODE,ALTERYX,BIRST,
		LOOKER,GOOGLE_DATA_STUDIO,
		SAS_VISUAL_ANALYTICS,
		GRAFANA,SPOTFIRE,PENTAHO,
		EXCEL_PLANILHA_GOOGLE,NAO_USA_FERRAMENTA ))
ORDER BY RESPONDENTES DESC;





